### ISSUE TITLE
Error when retrieving Trakt watchlist

### ISSUE THREAD

**Issue by mgmort** [a4k-openproject/plugin.video.openmeta#19]
I get an error when trying to view my Trakt movie watchlist through OpenMeta (watchlist contains about 300 items). All other OpenMeta Trakt features (tv watchlist, collection, next episodes) work just fine. My guess would be something malformed in the list that the Trakt API is returning to Openmeta, but I don't know how to check this.
Here's the section with the error from Kodi.log:

15:18:37.931 T:140618859468544   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: u'tv-movie'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.openmeta/addon.py", line 137, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.openmeta/resources/lib/xswift2.py", line 900, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/.kodi/addons/plugin.video.openmeta/resources/lib/xswift2.py", line 912, in _dispatch
                                                resp = view_func(**items)
                                              File "/storage/.kodi/addons/plugin.video.openmeta/resources/lib/nav_movies.py", line 526, in trakt_movies_watchlist
                                                return list_trakt_movies(result, '1', '1')
                                              File "/storage/.kodi/addons/plugin.video.openmeta/resources/lib/nav_movies.py", line 411, in list_trakt_movies
                                                movies = [meta_info.get_trakt_movie_metadata(item['movie'], genres_dict) for item in results]
                                              File "/storage/.kodi/addons/plugin.video.openmeta/resources/lib/meta_info.py", line 60, in get_trakt_movie_metadata
                                                info['genre'] = ' / '.join([genres_dict[x] for x in movie['genres']])
                                            KeyError: u'tv-movie'
                                            -->End of Python script error report<--
15:18:38.036 T:140618825901824   ERROR: GetDirectory - Error getting plugin://plugin.video.openmeta/my_trakt/movie_lists/movies/watchlist
15:18:38.037 T:140620638525568   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.openmeta/my_trakt/movie_lists/movies/watchlist) failed

**Comment by drinfernoo** [comment]
It appears this is because an entry in your watchlist is tagged as `'tv-movie'`, which isn't supported by OpenMeta, but it should be a pretty easy fix.

**Comment by TheDiggler** [comment]
With a fresh Kodi 18.3 build with only OpenMeta 1.4.5, still getting errors when accessing Next Up or Upcoming Episodes.

2019-07-31 04:21:54.740 T:13704   DEBUG: CAddonSettings[plugin.video.openmeta]: loading setting definitions
2019-07-31 04:21:54.740 T:13704   DEBUG: CAddonSettings[plugin.video.openmeta]: trying to load setting definitions from old format...
2019-07-31 04:21:54.741 T:13704   DEBUG: CAddonSettings[plugin.video.openmeta]: loading setting values
2019-07-31 04:22:09.601 T:12180    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to https://image.tmdb.org (easy=0x15940498310, multi=0x159406e5420)
2019-07-31 04:22:12.137 T:12180    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to https://image.tmdb.org (easy=0x159404a0180, multi=0x159406e3720)
2019-07-31 04:22:23.989 T:21576   DEBUG: Thread JobWorker 21576 terminating (autodelete)
2019-07-31 04:22:23.989 T:26272   DEBUG: Thread JobWorker 26272 terminating (autodelete)
2019-07-31 04:22:23.989 T:24448   DEBUG: Thread JobWorker 24448 terminating (autodelete)
2019-07-31 04:23:04.210 T:23476   DEBUG: CAESinkDirectSound::Deinitialize: Cleaning up
2019-07-31 04:24:54.457 T:19084   DEBUG: CAnnouncementManager - Announcement: OnScreensaverActivated from xbmc
2019-07-31 04:24:54.457 T:19084   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverActivated
2019-07-31 04:24:54.461 T:12180   DEBUG: CAddonSettings[screensaver.xbmc.builtin.dim]: loading setting definitions
2019-07-31 04:24:54.461 T:12180   DEBUG: CAddonSettings[screensaver.xbmc.builtin.dim]: trying to load setting definitions from old format...
2019-07-31 04:24:54.462 T:12180   DEBUG: ------ Window Init () ------
2019-07-31 04:30:56.697 T:19084   DEBUG: CAnnouncementManager - Announcement: OnScreensaverDeactivated from xbmc
2019-07-31 04:30:56.697 T:19084   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverDeactivated
2019-07-31 04:30:56.698 T:12180   DEBUG: ------ Window Init (Pointer.xml) ------
2019-07-31 04:30:57.700 T:12180   DEBUG: ------ Window Deinit () ------
2019-07-31 04:31:04.123 T:12180   DEBUG: ------ Window Deinit (Pointer.xml) ------
2019-07-31 04:31:05.491 T:12180   DEBUG: ------ Window Init (Pointer.xml) ------
2019-07-31 04:31:15.302 T:12180   DEBUG: ------ Window Deinit (Pointer.xml) ------
2019-07-31 04:32:51.351 T:12180   DEBUG: ------ Window Init (Pointer.xml) ------
2019-07-31 04:32:57.123 T:12180   DEBUG: ------ Window Deinit (Pointer.xml) ------
2019-07-31 04:33:24.993 T:13704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "C:\Users\digg\AppData\Roaming\Kodi\addons\plugin.video.openmeta\addon.py", line 157, in <module>
                                                plugin.run()
                                              File "C:\Users\digg\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\xswift2.py", line 917, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\digg\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\xswift2.py", line 929, in _dispatch
                                                resp = view_func(**items)
                                              File "C:\Users\digg\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\nav_tvshows.py", line 760, in trakt_tv_next_episodes
                                                return list_trakt_episodes(items)
                                              File "C:\Users\digg\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\nav_tvshows.py", line 457, in list_trakt_episodes
                                                'thumbnail': extradata['thumbnail'],
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
2019-07-31 04:33:24.993 T:13704   DEBUG: CPythonInvoker::onExecutionDone(26, C:\Users\digg\AppData\Roaming\Kodi\addons\plugin.video.openmeta\addon.py)
