### ISSUE TITLE
Fix error if pluginid not declared

### ISSUE THREAD

**Issue by rrosajp** [a4k-openproject/plugin.video.openmeta#29]
i think this error came back which was resolved in this commit
https://github.com/a4k-openproject/plugin.video.openmeta/commit/fd53cc48d466943561fdf4121e34aa66af07bc69#diff-cbe1264ed4e584d79589bb8a01727e02

**Comment by drinfernoo** [comment]
Can you elaborate?

**Comment by rrosajp** [comment]
@drinfernoo 
as of new update it give this error:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.TypeError'>
    Error Contents: argument of type 'NoneType' is not iterable
    Traceback (most recent call last):
      File "C:\Users\orion\AppData\Roaming\Kodi\addons\plugin.video.openmeta\addon.py", line 157, in <module>
        plugin.run()
      File "C:\Users\orion\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\xswift2.py", line 900, in run
        items = self._dispatch(self.request.path)
      File "C:\Users\orion\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\xswift2.py", line 912, in _dispatch
        resp = view_func(**items)
      File "C:\Users\orion\AppData\Roaming\Kodi\addons\plugin.video.openmeta\addon.py", line 19, in setdefaultplayers
        players = meta_players.get_players(i)
      File "C:\Users\orion\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\meta_players.py", line 34, in get_players
        if not player.is_empty():
      File "C:\Users\orion\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\meta_players.py", line 14, in is_empty
        if ',' in self.pluginid:
    TypeError: argument of type 'NoneType' is not iterable
    -->End of Python script error report<--
```
so it need to add that commit to master or just change the line # 14 from this:
`if ',' in self.pluginid:` 
To:
`if self.pluginid and ',' in self.pluginid:`
and then addon don't give the error and work as intended .

**Comment by drinfernoo** [comment]
I'll update this in the Kodi repo tomorrow 👌
