### ISSUE TITLE
[Bug] OpenMeta 'Next Page' does not work if in widget

### ISSUE THREAD

**Issue by SOOTTV** [a4k-openproject/plugin.video.openmeta#33]
**Describe the bug**
When using OpenMeta as a widget source the "next page" button doesn't open the next page

**To Reproduce**
1. Use OpenMeta as source for a widget
2. Click on 'Next Page'
3. See error

**Expected behavior**
Next page opens in OpenMeta

**Screenshots**
NA

**Platform**
- Kodi version (18.2 Leia)
- Device (PC, Nvidia Shield, Mac Pro)
- Operating System (Android, WIndows, Mac OSX)

**Log File**
Lmk if you need one

**Comment by diddy81** [comment]
worked fine for me with the most collected (trakt) list
what list are you using?

**Comment by diddy81** [comment]
seems the problem is specific to kodi 18

**Comment by drinfernoo** [comment]
Log snippet of the issue:

```
2019-07-15 09:50:29.212 T:5600   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'resources.lib.xswift2.NotFoundException'>
                                            Error Contents: No matching view found for /movies/tmdb/popular/
                                            Traceback (most recent call last):
                                              File "C:\Users\David\Desktop\kodi\Leia 18.2 Testing\portable_data\addons\plugin.video.openmeta\addon.py", line 157, in <module>
                                                plugin.run()
                                              File "C:\Users\David\Desktop\kodi\Leia 18.2 Testing\portable_data\addons\plugin.video.openmeta\resources\lib\xswift2.py", line 900, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\David\Desktop\kodi\Leia 18.2 Testing\portable_data\addons\plugin.video.openmeta\resources\lib\xswift2.py", line 919, in _dispatch
                                                raise NotFoundException('No matching view found for %s' % path)
                                            NotFoundException: No matching view found for /movies/tmdb/popular/
                                            -->End of Python script error report<--
```
