### ISSUE TITLE
[Bug] Can't open upcoming list in trakt anymore

### ISSUE THREAD

**Issue by disaacso** [a4k-openproject/plugin.video.openmeta#41]
**Describe the bug**

**To Reproduce**
1. Go to my trakt > shows > upcoming

**Expected behavior**
should open list,  instead errors out.

**Platform**
- Kodi version  18.2
- Device mecool m8s pro+
- Operating System libreelec 9.0.2
-OpenMeta v1.4.5

**Log File**
error snippet. 
[01_KODI.log](https://github.com/a4k-openproject/plugin.video.openmeta/files/3572477/01_KODI.log)

2019-09-03 21:43:12.299 T:2834297712   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.openmeta/addon.py", line 157, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.openmeta/resources/lib/xswift2.py", line 917, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/.kodi/addons/plugin.video.openmeta/resources/lib/xswift2.py", line 929, in _dispatch
                                                resp = view_func(**items)
                                              File "/storage/.kodi/addons/plugin.video.openmeta/resources/lib/nav_tvshows.py", line 740, in trakt_tv_upcoming_episodes
                                                return list_trakt_episodes(result)
                                              File "/storage/.kodi/addons/plugin.video.openmeta/resources/lib/nav_tvshows.py", line 457, in list_trakt_episodes
                                                'thumbnail': extradata['thumbnail'],
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
2019-09-03 21:43:13.265 T:2270516080   ERROR: GetDirectory - Error getting plugin://plugin.video.openmeta/my_trakt/tv_lists/tv_episodes_upcoming
2019-09-03 21:43:13.282 T:4093276176   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.openmeta/my_trakt/tv_lists/tv_episodes_upcoming) failed

**Comment by disaacso** [comment]
I rolled back to 1.4.4 and all works again

**Comment by disaacso** [comment]
update to 1.4.8 seems to have fixed this, the list shows up again, just no artwork for some reason.

**Comment by disaacso** [comment]
seems to be working so i'm closing issue

**Comment by drinfernoo** [comment]
Also, 1.4.9 fixed the artwork 👍
