### ISSUE TITLE
[Player Request]Fen player doesn't work anymore.  Is this the place to request fix?

### ISSUE THREAD

**Issue by Mahava** [a4k-openproject/plugin.video.openmeta#48]
Recently started getting this error in Kodi 18.4 log when using Fen player:

2019-11-03 15:16:13.625 T:3384   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: tvshow_meta() takes at least 3 arguments (2 given)
                                            Traceback (most recent call last):
                                              File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\plugin.video.fen\fen.py", line 88, in <module>
                                                params.get('plot'), params.get('meta'), literal_eval(params.get('library', 'False')), params.get('background'))
                                              File "C:\Users\xxxxx\AppData\Roaming\Kodi\addons\plugin.video.fen\resources\lib\modules\sources.py", line 46, in playback_prep
                                                self.meta = json.loads(meta) if meta else tikimeta.movie_meta('tmdb_id', tmdb_id) if vid_type == "movie" else tikimeta.tvshow_meta('tmdb_id', tmdb_id)
                                            TypeError: tvshow_meta() takes at least 3 arguments (2 given)
                                            -->End of Python script error report<--

**Comment by drinfernoo** [comment]
This actually appears to be an issue with Fen.
