### ISSUE TITLE
[Bug] Addon crashes immediately when I try to use (open) it

### ISSUE THREAD

**Issue by TalOrenshtein** [a4k-openproject/plugin.video.openmeta#50]
**Describe the bug**
Addon crashes immediately when I try to open the addon. I had kodi v18.1 and installed a fresh v18.4 on the same device after uninstalling and cleaning all the cache. didn't fix the problem.
The bug might be because my win10 username is at Hebrew.

LOG:

> 2019-11-12 19:30:55.246 T:22792   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.openmeta/
2019-11-12 19:30:55.256 T:23304   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.openmeta/) failed
2019-11-12 19:30:56.727 T:23304   ERROR: Control 55 in window 10025 has been asked to focus, but it can't
2019-11-12 19:30:56.922 T:9604   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: unable to open database file
                                            Traceback (most recent call last):
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.openmeta\addon.py", line 4, in <module>
                                                from resources.lib import menu_items
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\menu_items.py", line 1, in <module>
                                                from resources.lib import lists
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\lists.py", line 7, in <module>
                                                from resources.lib import nav_tvshows
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\nav_tvshows.py", line 9, in <module>
                                                from resources.lib import lib_tvshows
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\lib_tvshows.py", line 6, in <module>
                                                from resources.lib.TheTVDB import TVDB
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\TheTVDB.py", line 317, in <module>
                                                TVDB = Tvdb()
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\plugin.video.openmeta\resources\lib\TheTVDB.py", line 138, in __init__
                                                self.session = requests_cache.CachedSession(expire_after=21600, backend='sqlite', cache_name=os.path.join(plugin.storage_path, 'TheTVDB'))
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\script.module.requests-cache\lib\requests_cache\core.py", line 68, in __init__
                                                self.cache = backends.create_backend(backend, cache_name, backend_options)
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\script.module.requests-cache\lib\requests_cache\backends\__init__.py", line 63, in create_backend
                                                return registry[backend_name](cache_name, **options)
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\script.module.requests-cache\lib\requests_cache\backends\sqlite.py", line 28, in __init__
                                                self.responses = DbPickleDict(location + extension, 'responses', fast_save=fast_save)
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\script.module.requests-cache\lib\requests_cache\backends\storage\dbdict.py", line 58, in __init__
                                                with self.connection() as con:
                                              File "D:\Program Files\Kodi\system\python\Lib\contextlib.py", line 17, in __enter__
                                                return self.gen.next()
                                              File "C:\Users\��\AppData\Roaming\Kodi\addons\script.module.requests-cache\lib\requests_cache\backends\storage\dbdict.py", line 70, in connection
                                                con = sqlite.connect(self.filename)
                                            OperationalError: unable to open database file
                                            -->End of Python script error report<--
2019-11-12 19:30:56.947 T:23020   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.openmeta/
2019-11-12 19:30:56.957 T:23304   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.openmeta/) failed

**Comment by SerpentDrago** [comment]
> " installed a fresh v18.4 on the same device after uninstalling and cleaning all the cache" 

Are you sure the kodi data  folder was cleared first ? just uninstalling kodi on windows won't always clear it if at all ever . 

C:\Users\<your username>\AppData\Roaming\Kodi

Delete that entire folder , that will actually clean your kodi install . Then try re seting up meta / addons / etc 



If you think its your username causing issues , you could create a new user without any special char. and try it there  as a test. this would also use a fresh kodi appdata folder . so 2 birds one stone , then track down after .

**Comment by TalOrenshtein** [comment]
> > " installed a fresh v18.4 on the same device after uninstalling and cleaning all the cache"
> 
> Are you sure the kodi data folder was cleared first ? just uninstalling kodi on windows won't always clear it if at all ever .
> 
> C:\Users<your username>\AppData\Roaming\Kodi
> 
> Delete that entire folder , that will actually clean your kodi install . Then try re seting up meta / addons / etc
> 
> If you think its your username causing issues , you could create a new user without any special char. and try it there as a test. this would also use a fresh kodi appdata folder . so 2 birds one stone , then track down after .

I'm sure because I deleted it myself. And about my username,it's a bit of a problem to switch account because I'm using two screens and using the other one (with my stuff that are in that account) while using Kodi.

**Comment by diddy81** [comment]
As a test you could try a portable install of kodi  this would be less
hassle than making a new user to test and can be installed in any folder
here is a link about portable mode
https://kodi.wiki/view/Windows_FAQ#Portable_mode

**Comment by SerpentDrago** [comment]
^ great idea diddy 

yeh its simple as installing kodi to a folder with full write permissions (id recommend your desktop)  

Then making a shortcut to that kodi.exe with  -p at the end , then run though that shortcut , bam kodi will now store and write to the folder inside that install called portable_data

Its actually how i run kodi all the time ( i tend to have my main in one folder , and 2 testing versions in other folders , each with their own shortcuts )

**Comment by drinfernoo** [comment]
https://kodi.wiki/view/Windows_FAQ#Portable_mode

**Comment by TalOrenshtein** [comment]
It really was the special characters, portable version did fix it,thanks.
